CRM/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Data;
using CRM.Models;
using Microsoft.AspNetCore.Authorization;

namespace CRM.Controllers
{
    public class RolesController : Controller
    {
        private readonly CrmContext _context;

        public RolesController(CrmContext context)
        {
            _context = context;
        }

        // GET: Roles
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Role.ToListAsync());
        }

        // GET: Roles/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Role
                .FirstOrDefaultAsync(m => m.Id == id);
            //var user = await _context.User.ToListAsync(m => m.IdRole == role.Id);
            var user = await _context.User.Where(m => m.RoleId == role.Id).ToListAsync();
            var loggedUser = await _context.User.FirstOrDefaultAsync(m => m.Login == User.FindFirst("user").Value);
            ViewBag.userId = loggedUser.Id;
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.Message = role.RoleName + "s";
            return View(user);
        }

        //// GET: Roles/Create
        //[Authorize]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Roles/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Name")] Role role)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(role);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(role);
        //}

        //// GET: Roles/Edit/5
        //[Authorize]
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var role = await _context.Role.FindAsync(id);
        //    if (role == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(role);
        //}

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Role role)
        //{
        //    if (id != role.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(role);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!RoleExists(role.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(role);
        //}

        //// GET: Roles/Delete/5
        //[Authorize]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var role = await _context.Role
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (role == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(role);
        //}

        //// POST: Roles/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var role = await _context.Role.FindAsync(id);
        //    _context.Role.Remove(role);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool RoleExists(int id)
        //{
        //    return _context.Role.Any(e => e.Id == id);
        //}
    }
}

CRM/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Data;
using CRM.Models;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace CRM.Controllers
{
    public class UsersController : Controller
    {
        private readonly CrmContext _context;

        public UsersController(CrmContext context)
        {
            _context = context;
        }

        // GET: Users
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.User.ToListAsync());
        //}
        [Authorize]
        public async Task<IActionResult> Index(int page = 1, string sortExpression = "Id")
        {
            var qry = _context.User.AsNoTracking().OrderBy(p => p.Id);
            var model = await PagingList.CreateAsync(qry, 6, page, sortExpression, "Id");
            string[] roles = { "Admin" , "Moderator", "User"};
            ViewBag.roles = roles;
            return View(model);
        }

        // GET: Users/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            string[] roles = { "Admin", "Moderator", "User" };
            ViewBag.roles = roles;
            return View(user);
        }

        // GET: Users/Create
        [Authorize(Roles = "Admin, Moderator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( User user)
        {
            try
            {
                var user1 = await _context.User.AsNoTracking().FirstOrDefaultAsync(m => m.Login == user.Login);
                if (user1 == null) { 
                    user.Password = HashPassword(user.Password);
                    _context.Add(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                } else
                {
                    ModelState.AddModelError("", "Login is taken");
                    return View(user);
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Login is taken");
                return View(user);
            }
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }
            var adminnumber = await _context.User.CountAsync(m => m.RoleId == 1);


            //var user1 = await _context.User.FirstOrDefaultAsync(m => m.Login == user.Login);
            //var user2 = await _context.User.FindAsync(id);


            try
            {
                var user1 = await _context.User.AsNoTracking().FirstOrDefaultAsync(m => m.Login == user.Login);
                //var user1 = await _context.User.FirstOrDefaultAsync(m => m.Login == user.Login);
                if (user1 == null || id == user1.Id)
                {
                    //try
                    //{
                    if (ModelState.IsValid)
                    {
                        //_context.Update(user1);
                        //_context.Remove(user1);
                        ViewBag.Message = null;
                        if (adminnumber > 2 || user.RoleId == 1)
                        {
                            if (!IsMD5(user.Password))
                            {
                                user.Password = HashPassword(user.Password);
                            }
                            _context.Update(user);
                            await _context.SaveChangesAsync();
                            return RedirectToAction("Index");
                        } else
                        {
                            ViewBag.Message = String.Format("You cannot demote more admins! There must be at least 2 of them!");
                            return View(user);
                        }
                    }
                    return View(user);
                    //}
                    //catch (Exception)
                    //{
                    //    if (!UserExists(user.Id))
                    //    {
                    //        return NotFound();
                    //    }
                    //    else
                    //    {
                                
                    //    }
                    //}
                    //return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Login is taken");
                    return View(user);
                }
            } catch (Exception)
            {
                //throw;
                try
                {
                    if (ModelState.IsValid)
                    {
                        if (id != user.Id)
                        {
                            return NotFound();
                        }
                        if (!IsMD5(user.Password))
                        {
                            user.Password = HashPassword(user.Password);
                        }
                        _context.Update(user);
                        await _context.SaveChangesAsync();
                        return View(user);
                    } else
                    {
                        return View(user);
                    }
                }
                catch (Exception)
                {
                    //throw;
                    ModelState.AddModelError("", "Invalid data");
                    return View(user);
                }
            }
            
            
        }

        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            string[] roles = { "Admin", "Moderator", "User" };
            ViewBag.roles = roles;
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var user = await _context.User.FindAsync(id);
            var adminnumber = await _context.User.CountAsync(m => m.RoleId == 1);
            ViewBag.Message = null;
            if (adminnumber > 2 || user.RoleId != 1) {
                /*var companyNumber = await _context.Company.CountAsync(m => m.UserId == user.Id);
                while (companyNumber > 0)
                {
                    var companyToDelete = await _context.Company.FirstOrDefaultAsync(m => m.UserId == user.Id);
                    var noteNumber = await _context.Note.CountAsync(m => m.CompanyId == companyToDelete.Id);
                    while (noteNumber > 0)
                    {
                        var noteToDelete = await _context.Note.FirstOrDefaultAsync(m => m.CompanyId == companyToDelete.Id);
                        _context.Note.Remove(noteToDelete);
                        await _context.SaveChangesAsync();
                        noteNumber--;
                    }
                    var contactNumber = await _context.Contact.CountAsync(m => m.CompanyId == companyToDelete.Id);
                    while (contactNumber > 0)
                    {
                        var contactToDelete = await _context.Contact.FirstOrDefaultAsync(m => m.CompanyId == companyToDelete.Id);
                        _context.Contact.Remove(contactToDelete);
                        await _context.SaveChangesAsync();
                        contactNumber--;
                    }
                    _context.Company.Remove(companyToDelete);
                    await _context.SaveChangesAsync();
                    companyNumber--;
                }
                var noteNumberU = await _context.Note.CountAsync(m => m.UserId == user.Id);
                while (noteNumberU > 0)
                {
                    var noteToDelete = await _context.Note.FirstOrDefaultAsync(m => m.UserId == user.Id);
                    _context.Note.Remove(noteToDelete);
                    await _context.SaveChangesAsync();
                    noteNumberU--;
                }

CRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRM App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        nav ul li a {
            float: left;
            font-size: 16px;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        .active a{
            color: black;
            text-decoration: none;
            touch-action: none;
        }
        .wrapper {
	        margin-top: 80px;
            margin-bottom: 80px;
        }

        .form-signin {
            max-width: 380px;
            padding: 15px 35px 45px;
            margin: 0 auto;
            background-color: #fff;
            border: 1px solid rgba(0,0,0,0.1);
        }
        .form-signin-heading,
	    .checkbox {
	        margin-bottom: 30px;
	    }

	    .checkbox {
	        font-weight: normal;
	    }

	    .form-control {
	          position: relative;
	          font-size: 16px;
	          height: auto;
	          padding: 10px;
	    }

	    input[type="text"] {
	          margin-bottom: -1px;
	          border-bottom-left-radius: 0;
	          border-bottom-right-radius: 0;
	    }

	    input[type="password"] {
	          margin-bottom: 20px;
	          border-top-left-radius: 0;
	          border-top-right-radius: 0;
	    }
        td {
            @*word-break: break-all;*@
            @*word-break: break-word;*@
            word-wrap: break-word;
            line-break: auto;
        }
    }


    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">CRM App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CliesntsHistories" asp-action="Index">CliesntsHistories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StaffJobs" asp-action="Index">StaffJobs</a>
							</li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserTgs" asp-action="Index">UserTgs</a>
							</li>
                            @*@if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }*@
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRM App |
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Accounts" asp-action="Details" style="color:black">@User.FindFirst("user").Value</a>
                <span> </span>
                <span style="color:red">@User.FindFirst("role").Value</span>
                @*@foreach (var claim in User.Claims)
                {
                    @claim.Value
                    <span> </span>
                }
                @if (User.FindFirst("role").Value == "Admin")
                {
                    <span style="color:black">@User.FindFirst("role").Value</span>
                }*@
                <a asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a>
            }
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>